(require 'package)
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

;; Add in your own as you wish:
(defvar my-packages '(starter-kit
                      starter-kit-lisp
                      starter-kit-bindings
                      undo-tree
                      clojure-mode
                      slime
                      rainbow-delimiters
                     )
   "A list of packages to ensure are installed at launch.")

(dolist (p my-packages)
    (when (not (package-installed-p p))
        (package-install p)))

(add-to-list 'load-path "~/.emacs.d/evil")
(require 'evil)  
(evil-mode 1)

;(set-face-attribute 'default nil :font "Bitstream Vera Sans Mono-13")
(set-face-attribute 'default nil :font "Inconsolata-15")

(defun sweyla665742 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/665742/"
  (interactive)
  (color-theme-install
   '(sweyla665742
     ((background-color . "#000006")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#EED47E"))))
     (font-lock-constant-face ((t (:foreground "#94FFE4"))))
     (font-lock-builtin-face ((t (:foreground "#00FF49"))))
     (font-lock-function-name-face ((t (:foreground "#2EFAFF"))))
     (font-lock-variable-name-face ((t (:foreground "#00C23B"))))
     (font-lock-keyword-face ((t (:foreground "#36ED57"))))
     (font-lock-string-face ((t (:foreground "#4790A4"))))
     (font-lock-doc-string-face ((t (:foreground "#4790A4"))))
     (font-lock-type-face ((t (:foreground "#00F8DE"))))
     )))

(provide 'sweyla665742)

(load-theme 'manoj-dark)

(global-set-key (kbd "C-,") 'other-window)
(global-set-key (kbd "C-<") 'previous-buffer)
(global-set-key (kbd "C->") 'next-buffer)
(global-set-key [C-S-tab] 'previous-buffer)
(global-set-key [C-tab] 'next-buffer)
(global-set-key "\C- " 'hippie-expand)

(setq ibuffer-shrink-to-minimum-size t)
(setq ibuffer-always-show-last-buffer nil)
(setq ibuffer-sorting-mode 'recency)
(setq ibuffer-use-header-line t)
(global-set-key [(f12)] 'ibuffer)
(global-set-key [(f11)] 'buffer-menu)
(global-set-key [(f10)] 'ido-switch-buffer)

; Map shift-tab to reduce indent
; http://stackoverflow.com/questions/2249955/emacs-shift-tab-to-left-shift-the-block/2250155#2250155
(global-set-key (kbd "<S-tab>") 'un-indent-by-removing-4-spaces)
(defun un-indent-by-removing-4-spaces ()
  "remove 4 spaces from beginning of of line"
  (interactive)
  (save-excursion
    (save-match-data
      (beginning-of-line)
      ;; get rid of tabs at beginning of line
      (when (looking-at "^\\s-+")
        (untabify (match-beginning 0) (match-end 0)))
      (when (looking-at "^    ")
        (replace-match "")))))
